language: php

php:
  - 7.1.18
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse src tests --level=5
